### ISSUE TITLE
He is alive! 

### ISSUE THREAD

**Issue by opalczynski** [grski/braindead#30]
Great piece of software :)

**Comment by grski** [comment]
https://www.youtube.com/watch?v=Gzz-XSlMfSQ
will be back, soon

**Comment by sylvestrelucia** [comment]
Janusz was right.

**Comment by grski** [comment]
This is a crossover i did not expect.

-------- Oryginalna wiadomość --------
2 sty 2023, 23:13, Sylvestre Lucia napisał(a):
